# Generated by Django 4.2.14 on 2024-07-14 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_alter_stockrecord_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecord',
            name='partner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stockrecords', to='partner.partner', verbose_name='Partner'),
            preserve_default=False,
        ),
    ]
