# Generated by Django 4.2.14 on 2024-07-14 09:32

from django.db import migrations, models
import django.db.models.deletion
import oscar.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_attributeoption_code_attributeoptiongroup_code_and_more'),
        ('partner', '0008_alter_stockrecord_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractStockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_sku', models.CharField(max_length=128, verbose_name='Partner SKU')),
                ('price_currency', models.CharField(default=oscar.core.utils.get_default_currency, max_length=12, verbose_name='Currency')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price')),
                ('num_in_stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number in stock')),
                ('num_allocated', models.IntegerField(blank=True, null=True, verbose_name='Number allocated')),
                ('low_stock_threshold', models.PositiveIntegerField(blank=True, null=True, verbose_name='Low Stock Threshold')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_stockrecords', related_query_name='custom_stockrecord', to='partner.partner', verbose_name='Partner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_stockrecords', related_query_name='custom_stockrecord', to='catalogue.product', verbose_name='Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
